version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: OMS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1722001
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: oms-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/OMS
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1722001
      APP_JWT_SECRET: mysecretkeyisveryveryveryveryveryveryveryveryveryverylong&unique
      APP_JWT_EXPIRATION_MS: 600000

volumes:
  postgres_data:
